version: '3.8'

services:
  sqlapp2:
    build: .
    container_name: sqlapp2
    ports:
      - "${SERVER_PORT:-8080}:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
    volumes:
      - sqlapp2_data:/app/data
      - sqlapp2_logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  sqlapp2_data:
    name: sqlapp2_data
  sqlapp2_logs:
    name: sqlapp2_logs
